FROM node:20-alpine AS builder

WORKDIR /app
COPY report-mf/package*.json ./
RUN npm ci
COPY report-mf/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 3003
CMD ["nginx", "-g", "daemon off;"]
