FROM node:20-alpine AS builder

WORKDIR /app
COPY order-mf/package*.json ./
RUN npm ci
COPY order-mf/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 3002
CMD ["nginx", "-g", "daemon off;"]
