events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # ── customer-mf static server ─────────────────────────────
    server {
        listen 3001;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    # ── order-mf static server ────────────────────────────────
    server {
        listen 3002;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    # ── report-mf static server ───────────────────────────────
    server {
        listen 3003;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    # ── Gateway — main entry point ────────────────────────────
    server {
        listen 80;

        # Django API
        location /api/ {
            proxy_pass         http://backend:8000;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        # Host shell (catch-all)
        location / {
            proxy_pass         http://host:3000;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }
    }
}
